[tool.poetry]
name = "code-to-content-demo"
version = "0.1.0"
description = "A sample project to demonstrate Code-to-Content generation."
authors = ["Roo <roo@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2"